# Stage 1: Build Stage
FROM node:20.17.0-slim AS build

# Display build information
RUN echo "!!!!!! Building fullstack tasks application frontend image !!!!!!"

# Set the working directory inside the build container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# We are installing the same version that we have in the locally
RUN npm ci

# Copy the rest of the application code to the working directory
COPY . .

# Build the application
RUN npm run build:prod

# Stage 2: Production Stage
FROM nginx:stable-alpine AS production

# Set the working directory inside the final container
WORKDIR /usr/share/nginx/html

# Remove default nginx static assets
RUN rm -rf ./*

# Copy the built application from the build stage
COPY --from=build /app/dist .

# Copy the custom Nginx configuration to the Nginx configuration directory
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the application port
EXPOSE 80

# Start nginx server
CMD ["nginx", "-g", "daemon off;"]