name: Setup Node.js Environment

on:
  workflow_call:
    inputs:
      node-version:
        description: "The version of Node.js to install"
        type: string # Specify the type of the input
        default: "20.17.0" # Default Node.js version if none is provided

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      # Setup Node.js with the specified or default version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs['node-version'] }} # Use provided or default version
